### ISSUE TITLE
Gargoyle crashes on file load

### ISSUE THREAD

**Issue by tfranken90** [flathub/io.github.garglk.Gargoyle#3]
After picking a file to run, I get this crash on Fedora Silverblue 39

bocfel: ../../src/fccache.c:808: FcCacheFini: Assertion `fcCacheChains[i] == NULL' failed.

**Comment by cspiegel** [comment]
This should be fixed in #4.  This is a bug that was fixed in Gargoyle's git repo a while back, but I just plain forgot to update the Flatpak.  You can take a look at the test build in the pull request and see if it's working for you.

**Comment by tfranken90** [comment]
Seems to have fixed it 👍 Thanks a lot!
